<?php

/**
 * @file
 * Module file for the instagram_block module.
 */

/**
 * Implements hook_block_info().
 *
 * Defines the new instagram block.
 */
function instagram_block_block_info() {
  $blocks['instagram_block'] = array(
    'info' => t('Instagram Block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 *
 * Set values to be used when rendering the block later.
 */
function instagram_block_block_configure($delta = '') {
  $form = array();

  if ($delta == 'instagram_block') {
    // Create a keyed array of blank defaults for the storage variable.
    $empty = array(
      'user_id' => '',
      'access_token' => '',
      'count' => '4',
      'width' => '100',
      'height' => '100',
      'img_resolution' => 'thumbnail',
    );

    // Store data from variable in $form for now.
    $form['#data'] = variable_get('instagram_block_data', $empty);

    $form['user_id'] = array(
      '#type' => 'textfield',
      '#title' => t('User Id'),
      '#description' => t('Your unique Instagram user id. Eg. 460786510'),
      '#default_value' => isset($form['#data']['user_id']) ? $form['#data']['user_id'] : '',
    );

    $form['access_token'] = array(
      '#type' => 'textfield',
      '#title' => t('Access Token'),
      '#description' => t('Your Instagram access token. Eg. 460786509.ab103e5.a54b6834494643588d4217ee986384a8'),
      '#default_value' => isset($form['#data']['access_token']) ? $form['#data']['access_token'] : '',
    );

    $form['count'] = array(
      '#type' => 'textfield',
      '#title' => t('Number of images to display.'),
      '#default_value' => isset($form['#data']['count']) ? $form['#data']['count'] : '',
    );

    $form['width'] = array(
      '#type' => 'textfield',
      '#title' => t('Image width in pixels.'),
      '#default_value' => isset($form['#data']['width']) ? $form['#data']['width'] : '',
    );

    $form['height'] = array(
      '#type' => 'textfield',
      '#title' => t('Image height in pixels.'),
      '#default_value' => isset($form['#data']['height']) ? $form['#data']['height'] : '',
    );

    $image_options = array(
      'thumbnail' => t('Thumbnail Preview'),
      'low_resolution' => t('Low Resolution'),
      'standard_resolution' => t('Standard Resolution'),
    );

    $form['img_resolution'] = array(
      '#type' => 'select',
      '#title' => t('Image resolution'),
      '#description' => t('Choose the quality of the images you would like to display.'),
      '#options' => $image_options,
      '#default_value' => isset($form['#data']['img_resolution']) ? $form['#data']['img_resolution'] : '',
    );
  }

  return $form;
}

/**
 * Implements hook_block_save().
 *
 * Save the information from the configuration form to a drupal variable.
 */
function instagram_block_block_save($delta = '', $edit = array()) {
  if ($delta == 'instagram_block') {
    variable_set('instagram_block_data', $edit);
  }
}

/**
 * Implements hook_block_view().
 *
 * Fetches the instagram photos and creates a render array.
 */
function instagram_block_block_view($delta = '') {
  $block = array();

  if ($delta == 'instagram_block') {
    // Add instagram_block specific styles.
    drupal_add_css(drupal_get_path('module', 'instagram_block') . '/css/instagram-block.css');

    // Get configuration values.
    $values = variable_get('instagram_block_data', array());
    $img_resolution = isset($values['img_resolution']) ? $values['img_resolution'] : 'thumbnail';
    $content = array();

    // Check that block configuration is available.
    if (!isset($values['user_id']) || !isset($values['access_token'])) {
      // Remind user to fill in configuration.
      $content = instagram_block_get_configuration_reminder();
    }
    else {
      $url = "https://api.instagram.com/v1/users/" . $values['user_id'] . "/media/recent/?access_token=" . $values['access_token'] . "&count=" . $values['count'];
      $result = instagram_block_fetch_data($url);
      $result = json_decode($result);
      foreach ($result->data as $post) {
        $content['children'][$post->id] = array(
          '#markup' => '',
          '#theme' => 'instagram_block_image',
          '#post' => $post,
          '#href' => $post->link,
          '#src' => $post->images->{$img_resolution}->url,
          '#width' => $values['width'],
          '#height' => $values['height'],
        );
      }
    }

    $block['subject'] = 'Instagram Block';
    $block['content'] = $content;
  }

  return $block;
}

/**
 * Fetches instagram post information.
 */
function instagram_block_fetch_data($url) {
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_TIMEOUT, 20);
  $result = curl_exec($ch);
  curl_close($ch);
  return $result;
}

/**
 * Implements hook_menu().
 */
function instagram_block_menu() {
  $items['admin/config/content/instagram_block'] = array(
    'title' => 'Instagram Block',
    'description' => 'Configuration page for Instagram Block.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('instagram_block_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'instagram_block.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function instagram_block_theme() {
  return array(
    'instagram_block_image' => array(
      'variables' => array('height' => NULL,'width' => NULL, 'src' => NULL, 'href' => NULL, 'post' => NULL),
      'template' => 'instagram-block-image',
    ),
  );
}

/**
 * Builds render array to remind user to configure block settings.
 */
function instagram_block_get_configuration_reminder() {
  return array(
    '#markup' => t('Please don\'t forget to configure this block.')
  );
}
